### ISSUE TITLE
Takeoff Booster Fuel Burn

### ISSUE THREAD

**Issue by Jayhawker32** [MeSoftHorny/WTRTI#38] opened 2023-07-03 19:01 UTC
After using the boosters for takeoff the assumed fuel burn stays much higher than the actual fuel burn so the fuel timer calculation displays incorrect info afterward.

**Comment by MeSoftHorny** [comment] 2023-07-03 19:42
Not sure I understand the problem... the in-app fuel timer shows less time than the in-game one?
What plane it is?

**Comment by Jayhawker32** [comment] 2023-07-03 20:53
Any plane that has boosters on takeoff, A-4E US or Israel for instance. If you take off and use the booster it shows an increased fuel burn that never reduces. Pull the throttle to idle after takeoff and it will show something like 500 lbs/min still even with the engine shut off

**Comment by MeSoftHorny** [comment] 2023-07-04 14:15
Did some tests... Yeah, now I see.
The problem is that the program takes into account fuel_consume1 from localhost (on A4E it is the booster consumption), so after take-off and booster drop, the fuel_consume1 is stuck on the last the booster fuel consumption.
Looking at the code, the bug has been around since v2.1. So if you really need the fuel indicators, try to use the v2.0.2.

Anyway. Thanks for noticing. I'll fix it in the future update.

**Comment by Jayhawker32** [comment] 2023-07-04 16:52
Gotcha, glad you understand. Don't need it all that bad just noticed it so figured I would report it.

Cheers!

**Comment by MeSoftHorny** [comment] 2023-09-01 19:32
Fixed in v2.2

**Closed by MeSoftHorny** 2023-09-01 19:32 UTC
